import { StyleSheet, Platform } from "react-native";
import { RADIUS, SHADOWS } from "@/src/constants/colors";

export const styles = StyleSheet.create({
  // ── Layout ────────────────────────────────────────────────────────────
  container: {
    flex: 1,
    backgroundColor: "#0B141A",
  },
  gradientBackground: {
    ...StyleSheet.absoluteFillObject,
  },
  safeArea: {
    flex: 1,
  },
  keyboardAvoiding: {
    flex: 1,
  },

  // ── WhatsApp Style Header ──────────────────────────────────────────────
  headerContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 6,
    paddingTop: 4,
    paddingBottom: 8,
    backgroundColor: "rgba(11, 20, 26, 0.95)",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.05)",
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    gap: 6,
  },
  backButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    justifyContent: "center",
    alignItems: "center",
  },
  avatarContainer: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#202C33",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  avatarImage: {
    width: "100%",
    height: "100%",
  },
  avatarLetter: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 16,
    color: "#FFFFFF",
  },
  headerTextWrap: {
    flex: 1,
    justifyContent: "center",
    marginLeft: 2,
  },
  headerName: {
    fontFamily: "Fredoka_600SemiBold",
    fontSize: 16,
    color: "#E9EDEF",
    lineHeight: 20,
  },
  headerStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 1,
  },
  onlineText: {
    fontFamily: "Fredoka_400Regular",
    fontSize: 12,
    color: "#00A884",
  },
  offlineText: {
    fontFamily: "Fredoka_400Regular",
    fontSize: 12,
    color: "#8696A0",
  },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
  },
  headerActionBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
  },

  // ── Date Separator Chip ───────────────────────────────────────────────
  dateSeparatorWrap: {
    alignItems: "center",
    marginVertical: 10,
  },
  dateSeparator: {
    backgroundColor: "rgba(24, 34, 41, 0.92)",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.25,
    shadowRadius: 1.5,
    elevation: 2,
  },
  dateSeparatorText: {
    fontFamily: "Fredoka_600SemiBold",
    fontSize: 11.5,
    color: "#8696A0",
  },

  // ── WhatsApp Style Bubbles ─────────────────────────────────────────────
  bubbleRowMine: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginVertical: 2,
    paddingLeft: 46,
    paddingRight: 8,
  },
  bubbleRowPartner: {
    flexDirection: "row",
    justifyContent: "flex-start",
    marginVertical: 2,
    paddingRight: 46,
    paddingLeft: 8,
  },
  bubbleMineWrapper: {
    maxWidth: "84%",
  },
  bubblePartnerWrapper: {
    maxWidth: "84%",
  },
  bubbleMine: {
    borderRadius: 12,
    borderTopRightRadius: 2,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
    elevation: 1,
  },
  bubbleMineGradient: {
    paddingHorizontal: 10,
    paddingTop: 6,
    paddingBottom: 6,
  },
  bubbleMineText: {
    fontFamily: "Fredoka_400Regular",
    fontSize: 15,
    color: "#E9EDEF",
    lineHeight: 20,
    marginRight: 6,
  },
  bubblePartner: {
    borderRadius: 12,
    borderTopLeftRadius: 2,
    backgroundColor: "#202C33",
    paddingHorizontal: 10,
    paddingTop: 6,
    paddingBottom: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
    elevation: 1,
  },
  bubblePartnerText: {
    fontFamily: "Fredoka_400Regular",
    fontSize: 15,
    color: "#E9EDEF",
    lineHeight: 20,
    marginRight: 6,
  },
  bubbleContentRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "flex-end",
    justifyContent: "flex-end",
  },
  metaRowMine: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-end",
    marginLeft: "auto",
    gap: 3,
    marginBottom: 1,
  },
  metaRowPartner: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-end",
    marginLeft: "auto",
    marginBottom: 1,
  },
  timeMineText: {
    fontFamily: "Fredoka_400Regular",
    fontSize: 11,
    color: "rgba(255, 255, 255, 0.75)",
    lineHeight: 13,
  },
  timePartnerText: {
    fontFamily: "Fredoka_400Regular",
    fontSize: 11,
    color: "#8696A0",
    lineHeight: 13,
  },
  tickIcon: {
    marginLeft: 1,
  },
  failedRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    justifyContent: "flex-end",
    marginTop: 2,
  },
  failedText: {
    fontFamily: "Fredoka_400Regular",
    fontSize: 11,
    color: "#EF4444",
  },

  // ── Image Bubbles ─────────────────────────────────────────────────────
  imageContainer: {
    width: 210,
    height: 190,
    borderRadius: 8,
    overflow: "hidden",
    position: "relative",
  },
  bubbleImage: {
    width: "100%",
    height: "100%",
  },
  imageTimeBadgeMine: {
    position: "absolute",
    right: 6,
    bottom: 6,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  imageTimeBadgePartner: {
    position: "absolute",
    right: 6,
    bottom: 6,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 8,
  },

  // ── WhatsApp Style Input Bar ───────────────────────────────────────────
  inputBarWrapper: {
    backgroundColor: "transparent",
    paddingHorizontal: 6,
    paddingTop: 4,
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 6,
  },
  inputPill: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#202C33",
    borderRadius: 25,
    paddingHorizontal: 8,
    minHeight: 48,
    maxHeight: 120,
  },
  inputField: {
    flex: 1,
    paddingVertical: Platform.OS === "ios" ? 10 : 8,
    paddingHorizontal: 8,
    fontFamily: "Fredoka_400Regular",
    fontSize: 15.5,
    color: "#FFFFFF",
    lineHeight: 20,
  },
  inputIconBtn: {
    padding: 6,
    justifyContent: "center",
    alignItems: "center",
  },
  sendButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 3,
  },
  sendButtonGradient: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
  },

  // ── Message List & Load States ─────────────────────────────────────────
  listContent: {
    paddingHorizontal: 4,
    paddingTop: 10,
    paddingBottom: 8,
    flexGrow: 1,
    justifyContent: "flex-end",
  },
  loadMoreButton: {
    alignSelf: "center",
    paddingVertical: 5,
    paddingHorizontal: 12,
    borderRadius: RADIUS.pill,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    marginBottom: 8,
  },
  loadMoreText: {
    fontFamily: "Fredoka_400Regular",
    fontSize: 11.5,
    color: "#8696A0",
  },
  emptyContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 32,
  },
  emptyEmoji: {
    fontSize: 44,
  },
  emptyText: {
    fontFamily: "Fredoka_600SemiBold",
    fontSize: 17,
    color: "#E9EDEF",
    textAlign: "center",
  },
  emptySubtext: {
    fontFamily: "Fredoka_400Regular",
    fontSize: 13,
    color: "#8696A0",
    textAlign: "center",
  },
  centeredContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 32,
    gap: 16,
  },
  centeredText: {
    fontFamily: "Fredoka_400Regular",
    fontSize: 14,
    color: "#8696A0",
    textAlign: "center",
    lineHeight: 20,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 22,
    paddingVertical: 12,
    borderRadius: RADIUS.button,
    backgroundColor: "#00A884",
    ...SHADOWS.primaryAction,
  },
  actionButtonText: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 15,
    color: "#FFFFFF",
  },
  blockingCard: {
    backgroundColor: "rgba(32, 44, 51, 0.8)",
    borderRadius: RADIUS.card,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    padding: 26,
    alignItems: "center",
    gap: 14,
    marginHorizontal: 20,
    marginTop: 40,
  },
  blockingIconWrap: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: "rgba(0, 168, 132, 0.15)",
    justifyContent: "center",
    alignItems: "center",
  },
  blockingTitle: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 19,
    color: "#E9EDEF",
    textAlign: "center",
  },
  blockingText: {
    fontFamily: "Fredoka_400Regular",
    fontSize: 14,
    color: "#8696A0",
    textAlign: "center",
    lineHeight: 20,
    paddingHorizontal: 8,
  },

  // ── Theme Customization Modal ──────────────────────────────────────────
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.75)",
    justifyContent: "flex-end",
  },
  modalDismissArea: {
    flex: 1,
  },
  modalSheet: {
    backgroundColor: "#161D22",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: Platform.OS === "ios" ? 34 : 22,
    gap: 16,
  },
  modalDragHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    alignSelf: "center",
    marginBottom: 4,
  },
  modalHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  modalTitle: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 18,
    color: "#E9EDEF",
  },
  modalCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    justifyContent: "center",
    alignItems: "center",
  },
  themeSection: {
    gap: 10,
  },
  themeSectionTitle: {
    fontFamily: "Fredoka_600SemiBold",
    fontSize: 14,
    color: "#CBD5E1",
  },
  themeScrollRow: {
    gap: 12,
    paddingVertical: 4,
  },
  themeCard: {
    alignItems: "center",
    gap: 6,
  },
  themeCircleWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: "transparent",
    padding: 2,
    justifyContent: "center",
    alignItems: "center",
  },
  themeCircleActive: {
    borderColor: "#00A884",
  },
  themeCircle: {
    width: "100%",
    height: "100%",
    borderRadius: 21,
    justifyContent: "center",
    alignItems: "center",
  },
  themeName: {
    fontFamily: "Fredoka_400Regular",
    fontSize: 11,
    color: "#8696A0",
  },
  themeNameActive: {
    color: "#E9EDEF",
    fontFamily: "Fredoka_600SemiBold",
  },
  doneButton: {
    backgroundColor: "#00A884",
    borderRadius: RADIUS.button,
    paddingVertical: 13,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 4,
    ...SHADOWS.primaryAction,
  },
  doneButtonText: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 16,
    color: "#FFFFFF",
  },
});
