import { StyleSheet } from "react-native";
import { COLORS } from "@/src/constants/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  gradientBackground: {
    ...StyleSheet.absoluteFillObject,
  },
  safeArea: {
    flex: 1,
    paddingHorizontal: 20,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 12,
    paddingBottom: 16,
  },
  greetingContainer: {
    gap: 4,
  },
  headerLogo: {
    width: 44,
    height: 44,
  },
  appName: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 26,
    color: "#FFFFFF",
  },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(255, 77, 109, 0.15)",
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 12,
    alignSelf: "flex-start",
  },
  statusText: {
    fontSize: 12,
    color: "#FF8FA3",
    fontWeight: "600",
  },
  scrollContent: {
    paddingBottom: 110,
  },
  greetingSection: {
    marginBottom: 20,
    marginTop: 4,
  },
  greetingTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 6,
  },
  greetingTitle: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 24,
    color: "#FFFFFF",
  },
  greetingEmoji: {
    fontSize: 22,
  },
  greetingSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    color: COLORS.textMuted,
  },
  heroCard: {
    borderRadius: 24,
    overflow: "hidden",
    marginBottom: 26,
    shadowColor: "#E11D48",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 14,
    elevation: 8,
  },
  heroGradient: {
    padding: 20,
    minHeight: 180,
    justifyContent: "space-between",
  },
  heroFlagsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  heroFlagBadgeLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(0, 0, 0, 0.25)",
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 14,
  },
  heroFlagBadgeRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(0, 0, 0, 0.25)",
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 14,
  },
  heroFlagText: {
    fontSize: 12,
    color: "#FFFFFF",
    fontWeight: "700",
  },
  heroCenterContent: {
    alignItems: "center",
    marginVertical: 4,
  },
  heroTitle: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 26,
    lineHeight: 32,
    color: "#FFFFFF",
    textAlign: "center",
  },
  heroSubtitle: {
    fontSize: 13,
    color: "rgba(255, 255, 255, 0.85)",
    textAlign: "center",
    marginTop: 6,
    fontStyle: "italic",
  },
  heroFooter: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 12,
  },
  heroPlayBadge: {
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
  },
  heroPlayText: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 13,
    color: "#E11D48",
  },
  sectionContainer: {
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 14,
  },
  sectionTitle: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 18,
    color: "#FFFFFF",
  },
  toolsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 12,
  },
  toolCard: {
    width: "31%",
    aspectRatio: 0.95,
    borderRadius: 20,
    padding: 10,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 3,
  },
  toolIconContainer: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 8,
  },
  toolTitle: {
    fontFamily: "Fredoka_600SemiBold",
    fontSize: 12,
    color: "#FFFFFF",
    textAlign: "center",
    lineHeight: 15,
  },
  todaysCard: {
    backgroundColor: "rgba(255, 77, 109, 0.12)",
    borderWidth: 1.5,
    borderColor: "rgba(255, 77, 109, 0.25)",
    borderRadius: 22,
    padding: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  todaysCardLeft: {
    flex: 1,
    paddingRight: 12,
  },
  todaysCardQuote: {
    fontFamily: "Fredoka_600SemiBold",
    fontSize: 15,
    lineHeight: 22,
    color: "#FFFFFF",
    marginBottom: 8,
  },
  todaysCardTapPrompt: {
    fontSize: 12,
    color: "#FF8FA3",
    fontWeight: "700",
  },
  todaysCardRight: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "rgba(255, 77, 109, 0.2)",
    justifyContent: "center",
    alignItems: "center",
  },
  inviteBanner: {
    backgroundColor: "rgba(255, 255, 255, 0.06)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
    borderRadius: 20,
    padding: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 6,
    marginBottom: 16,
  },
  inviteBannerTextContainer: {
    flex: 1,
    marginRight: 12,
  },
  inviteBannerTitle: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 15,
    color: "#FFFFFF",
    marginBottom: 4,
  },
  inviteBannerSubtitle: {
    fontSize: 12,
    lineHeight: 16,
    color: COLORS.textMuted,
  },
  inviteBannerButton: {
    backgroundColor: "#FF4D6D",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 16,
  },
  inviteBannerButtonText: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 13,
    color: "#FFFFFF",
  },
  signOutRow: {
    alignItems: "center",
    paddingVertical: 16,
  },
  signOutText: {
    fontSize: 14,
    color: "#94A3B8",
    fontWeight: "600",
  },
});
