export const ROUTES = {
  SPLASH: "/",
  WELCOME: "/welcome",
  LOGIN: "/login",
  ONBOARDING_NAME: "/onboarding-name",
  ONBOARDING: "/onboarding",
  DATE_IDEAS: "/date-ideas",
  PLAY_COMPARE: "/play-compare",
  MEMORIES: "/memories",
  READY: "/ready",
  INVITE_PARTNER: "/invite-partner",
  HOME: "/home",
  PROFILE: "/profile",
  LOVE_MATCH: "/love-match",
  LOVE_MATCH_RESULT: "/love-match-result",
  CRUSH_CALCULATOR: "/crush-calculator",
  CRUSH_CALCULATOR_RESULT: "/crush-calculator-result",
  TWENTY_ONE_QUESTIONS: "/twenty-one-questions",
  COUPLE_QUIZ: "/couple-quiz",
  COUPLE_QUIZ_PLAY: "/couple-quiz-play",
  COUPLE_QUIZ_REVIEW: "/couple-quiz-review",
  COUPLE_QUIZ_RESULT: "/couple-quiz-result",
  EDIT_PROFILE: "/edit-profile",
  ABOUT: "/about",
  FEEDBACK: "/feedback",
  TERMS: "/terms",
  PRIVACY: "/privacy",
} as const;

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES];
