import { StyleSheet } from "react-native";
import { COLORS } from "@/src/constants/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  gradientBackground: {
    ...StyleSheet.absoluteFillObject,
  },
  safeArea: {
    flex: 1,
    paddingHorizontal: 24,
    justifyContent: "space-between",
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingTop: 12,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    justifyContent: "center",
    alignItems: "center",
  },
  scrollContent: {
    paddingTop: 28,
    paddingBottom: 16,
  },
  titleContainer: {
    marginBottom: 28,
  },
  title: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 34,
    lineHeight: 40,
    color: "#FFFFFF",
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 15,
    lineHeight: 22,
    color: COLORS.textMuted,
  },
  codeCard: {
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.14)",
    borderRadius: 24,
    paddingVertical: 28,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 4,
  },
  codeText: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 40,
    letterSpacing: 8,
    color: "#FFFFFF",
    marginBottom: 6,
  },
  expiryText: {
    fontSize: 14,
    color: "#CBD5E1",
    fontWeight: "500",
  },
  refreshRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 8,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 14,
  },
  refreshText: {
    fontSize: 13,
    color: "#FF8FA3",
    fontWeight: "600",
  },
  inviteButton: {
    height: 56,
    borderRadius: 28,
    overflow: "hidden",
    shadowColor: "#FF4D6D",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 6,
  },
  inviteButtonGradient: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 28,
  },
  inviteButtonIcon: {
    marginRight: 8,
  },
  inviteButtonText: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 17,
    color: "#FFFFFF",
    letterSpacing: 0.3,
  },
  dividerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 24,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: "rgba(255, 255, 255, 0.12)",
  },
  dividerText: {
    marginHorizontal: 16,
    fontSize: 14,
    color: "#94A3B8",
    fontWeight: "600",
  },
  partnerInputSection: {
    marginBottom: 20,
  },
  partnerInputHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#CBD5E1",
  },
  pasteButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  pasteButtonText: {
    fontSize: 13,
    color: "#FFFFFF",
    fontWeight: "600",
  },
  inputCard: {
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.14)",
    borderRadius: 20,
    height: 60,
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  textInput: {
    fontSize: 22,
    color: "#FFFFFF",
    letterSpacing: 6,
    fontFamily: "Fredoka_700Bold",
    textAlign: "center",
  },
  connectButton: {
    height: 52,
    borderRadius: 26,
    overflow: "hidden",
    marginTop: 14,
    shadowColor: "#FFA45C",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  connectButtonGradient: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 26,
  },
  connectButtonText: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 16,
    color: "#FFFFFF",
  },
  footer: {
    paddingBottom: 16,
    alignItems: "center",
  },
  laterButton: {
    paddingVertical: 12,
    paddingHorizontal: 20,
  },
  laterButtonText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#94A3B8",
    textAlign: "center",
  },
});
