import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  container: {
    position: "absolute",
    bottom: Platform.OS === "ios" ? 24 : 16,
    left: 16,
    right: 16,
    alignItems: "center",
    zIndex: 100,
  },
  pillBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(26, 23, 34, 0.95)",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 36,
    height: 66,
    paddingHorizontal: 8,
    width: "100%",
    maxWidth: 420,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.45,
    shadowRadius: 18,
    elevation: 10,
    position: "relative",
  },
  indicator: {
    position: "absolute",
    top: 8,
    height: 48,
    backgroundColor: "rgba(255, 255, 255, 0.16)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.18)",
    borderRadius: 24,
    shadowColor: "rgba(255, 255, 255, 0.2)",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
  },
  tabButton: {
    flex: 1,
    height: 50,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1,
  },
});
