import { StyleSheet } from "react-native";
import { COLORS, RADIUS } from "@/src/constants/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.bgPinkLight,
  },
  gradientBackground: {
    ...StyleSheet.absoluteFillObject,
  },
  safeArea: {
    flex: 1,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 12,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: RADIUS.circleBack,
    backgroundColor: "rgba(255, 255, 255, 0.85)",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 4,
    elevation: 2,
  },
  headerCenter: {
    flex: 1,
    alignItems: "center",
    gap: 4,
  },
  headerTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  headerTitle: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 22,
    color: COLORS.textPrimary,
  },
  headerSubtitle: {
    fontSize: 12,
    color: COLORS.textSecondary,
    textAlign: "center",
    lineHeight: 16,
    paddingHorizontal: 16,
  },
  headerSpacer: {
    width: 40,
  },

  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 32,
    gap: 18,
  },

  mainCard: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.card,
    padding: 20,
    shadowColor: COLORS.primaryLight,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 4,
    alignItems: "center",
  },

  illustrationWrap: {
    width: "100%",
    marginBottom: 16,
    borderRadius: RADIUS.cardSmall,
    overflow: "hidden",
  },

  cardTitle: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 20,
    color: COLORS.textPrimary,
    textAlign: "center",
    marginBottom: 8,
  },
  cardDescription: {
    fontFamily: "Fredoka_400Regular",
    fontSize: 14,
    color: COLORS.textSecondary,
    textAlign: "center",
    lineHeight: 20,
    paddingHorizontal: 12,
    marginBottom: 20,
  },

  featureRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    width: "100%",
    backgroundColor: COLORS.pillBg,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 18,
    marginBottom: 10,
  },
  featureIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.white,
    justifyContent: "center",
    alignItems: "center",
  },
  featureText: {
    flex: 1,
    fontFamily: "Fredoka_600SemiBold",
    fontSize: 13.5,
    color: COLORS.textPrimary,
  },

  actionButton: {
    width: "100%",
    height: 56,
    borderRadius: RADIUS.button,
    overflow: "hidden",
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 5,
    marginTop: 10,
  },
  actionButtonDisabled: {
    opacity: 0.5,
    shadowOpacity: 0.1,
  },
  actionButtonGradient: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    borderRadius: RADIUS.button,
  },
  actionButtonText: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 17,
    color: COLORS.white,
    letterSpacing: 0.3,
  },

  blockingCard: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.card,
    padding: 24,
    alignItems: "center",
    shadowColor: COLORS.primaryLight,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 4,
    marginTop: 20,
  },
  blockingIconWrap: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: COLORS.bgPinkAlt,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
  },
  blockingTitle: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 19,
    color: COLORS.textPrimary,
    textAlign: "center",
    marginBottom: 8,
  },
  blockingText: {
    fontFamily: "Fredoka_400Regular",
    fontSize: 14,
    color: COLORS.textSecondary,
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 20,
    paddingHorizontal: 10,
  },

  pendingPulseBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: COLORS.bgPinkAlt,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 20,
    marginBottom: 16,
  },
  pendingPulseText: {
    fontFamily: "Fredoka_600SemiBold",
    fontSize: 12,
    color: COLORS.primaryVibrant,
  },

  errorBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: COLORS.errorLight,
    borderRadius: RADIUS.input,
    padding: 12,
    width: "100%",
    marginBottom: 14,
  },
  errorText: {
    fontFamily: "Fredoka_600SemiBold",
    fontSize: 13,
    color: COLORS.errorText,
    flex: 1,
  },
});
