import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFF0F4",
  },
  gradientBackground: {
    ...StyleSheet.absoluteFillObject,
  },
  safeArea: {
    flex: 1,
    paddingHorizontal: 20,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 8,
    paddingBottom: 12,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.7)",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  headerTitleContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  headerHeartIcon: {
    shadowColor: "#FF4D6D",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  headerTitle: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 22,
    color: "#1E1B26",
  },
  headerSpacer: {
    width: 40,
  },
  scrollContent: {
    paddingTop: 8,
    paddingBottom: 32,
  },
  subtitleContainer: {
    alignItems: "center",
    marginBottom: 28,
    marginTop: 4,
  },
  subtitle: {
    fontSize: 14,
    lineHeight: 20,
    color: "#64748B",
    textAlign: "center",
    paddingHorizontal: 16,
  },
  avatarsRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    marginBottom: 24,
    gap: 16,
  },
  avatarCard: {
    flex: 1,
    aspectRatio: 1,
    maxWidth: 160,
    backgroundColor: "#FFFFFF",
    borderRadius: 80,
    justifyContent: "center",
    alignItems: "center",
    padding: 12,
    shadowColor: "#FF8FA3",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 4,
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.9)",
  },
  avatarIconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#F8FAFC",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 6,
  },
  avatarLabel: {
    fontSize: 12,
    fontWeight: "500",
    color: "#94A3B8",
    marginBottom: 4,
  },
  nameInputContainer: {
    width: "100%",
    minHeight: 32,
    justifyContent: "center",
    alignItems: "center",
  },
  nameInput: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 16,
    color: "#0F172A",
    textAlign: "center",
    width: "100%",
    paddingVertical: 0,
    paddingHorizontal: 6,
    includeFontPadding: false,
  },
  datesRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 28,
  },
  dateCard: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    paddingVertical: 12,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.8)",
  },
  dateIconBox: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "#F1F5F9",
    justifyContent: "center",
    alignItems: "center",
  },
  dateTextBox: {
    flex: 1,
  },
  dateLabel: {
    fontSize: 11,
    fontWeight: "500",
    color: "#94A3B8",
    marginBottom: 2,
  },
  dateValue: {
    fontFamily: "Fredoka_600SemiBold",
    fontSize: 13,
    color: "#1E293B",
  },
  calculateButton: {
    height: 56,
    borderRadius: 28,
    overflow: "hidden",
    shadowColor: "#FF4D6D",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 5,
    marginTop: 8,
  },
  calculateButtonDisabled: {
    opacity: 0.5,
    shadowOpacity: 0.1,
  },
  calculateGradient: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 28,
  },
  calculateText: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 17,
    color: "#FFFFFF",
    letterSpacing: 0.3,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  modalContainer: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 34,
    maxHeight: 460,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  modalTitle: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 18,
    color: "#1E1B26",
  },
  modalCloseButton: {
    padding: 6,
  },
  modalColumnsRow: {
    flexDirection: "row",
    height: 220,
    gap: 10,
    marginBottom: 20,
  },
  pickerColumn: {
    flex: 1,
    backgroundColor: "#F8FAFC",
    borderRadius: 16,
    overflow: "hidden",
  },
  pickerItem: {
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    marginHorizontal: 4,
    marginVertical: 2,
  },
  pickerItemSelected: {
    backgroundColor: "#FF4D6D",
  },
  pickerItemText: {
    fontFamily: "Fredoka_600SemiBold",
    fontSize: 14,
    color: "#475569",
  },
  pickerItemTextSelected: {
    color: "#FFFFFF",
    fontFamily: "Fredoka_700Bold",
  },
  modalDoneButton: {
    height: 50,
    borderRadius: 25,
    overflow: "hidden",
  },
  modalDoneGradient: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  modalDoneText: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 16,
    color: "#FFFFFF",
  },
});
