import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFF5F7",
  },
  gradientBackground: {
    ...StyleSheet.absoluteFillObject,
  },
  safeArea: {
    flex: 1,
  },

  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 12,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.8)",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 4,
    elevation: 2,
  },
  headerCenter: {
    flex: 1,
    alignItems: "center",
    gap: 4,
  },
  headerTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  headerTitle: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 22,
    color: "#1E1B26",
  },
  headerSubtitle: {
    fontSize: 12,
    color: "#64748B",
    textAlign: "center",
    lineHeight: 16,
    paddingHorizontal: 16,
  },
  headerSpacer: {
    width: 40,
  },

  progressBarContainer: {
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  progressBarTrack: {
    height: 5,
    backgroundColor: "rgba(0,0,0,0.06)",
    borderRadius: 3,
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    borderRadius: 3,
  },

  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },

  questionCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 28,
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 24,
    shadowColor: "#FF8FA3",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 4,
  },
  progressCounter: {
    fontFamily: "Fredoka_600SemiBold",
    fontSize: 14,
    color: "#475569",
    textAlign: "center",
    marginBottom: 14,
    letterSpacing: 0.5,
  },
  questionText: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 21,
    color: "#1E1B26",
    textAlign: "center",
    lineHeight: 28,
    marginBottom: 24,
    paddingHorizontal: 6,
  },

  optionsContainer: {
    gap: 12,
  },
  optionPill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FBF3F4",
    borderRadius: 26,
    paddingVertical: 14,
    paddingHorizontal: 18,
    gap: 12,
    borderWidth: 1.5,
    borderColor: "transparent",
  },
  optionPillSelected: {
    borderColor: "#FF2D6C",
    backgroundColor: "#FFE9EF",
  },
  optionIcon: {
    width: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  optionText: {
    flex: 1,
    fontFamily: "Fredoka_600SemiBold",
    fontSize: 14.5,
    color: "#1E1B26",
    lineHeight: 20,
  },
  optionTextSelected: {
    color: "#FF2D6C",
  },

  footer: {
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 20,
    paddingBottom: 24,
    paddingTop: 8,
  },
  prevButton: {
    flex: 1,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#FFFFFF",
    borderWidth: 1.5,
    borderColor: "#F1F5F9",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    gap: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  prevButtonDisabled: {
    opacity: 0.45,
    shadowOpacity: 0,
    elevation: 0,
  },
  prevButtonText: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 16,
    color: "#1E1B26",
  },
  prevButtonTextDisabled: {
    color: "#94A3B8",
  },
  nextButton: {
    flex: 1,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#FF2D6C",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    gap: 6,
    shadowColor: "#FF2D6C",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.28,
    shadowRadius: 8,
    elevation: 4,
  },
  nextButtonDisabled: {
    backgroundColor: "#CBD5E1",
    shadowOpacity: 0.05,
    elevation: 0,
  },
  nextButtonText: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 16,
    color: "#FFFFFF",
  },

  toastContainer: {
    position: "absolute",
    bottom: 110,
    left: 24,
    right: 24,
    backgroundColor: "#1E1B26",
    borderRadius: 20,
    paddingVertical: 16,
    paddingHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 10,
  },
  toastText: {
    fontFamily: "Fredoka_600SemiBold",
    fontSize: 15,
    color: "#FFFFFF",
    flex: 1,
  },
});
