import { StyleSheet } from "react-native";
import { COLORS, RADIUS } from "@/src/constants/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.bgPinkLight,
  },
  gradientBackground: {
    ...StyleSheet.absoluteFillObject,
  },
  safeArea: {
    flex: 1,
  },

  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 12,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: RADIUS.circleBack,
    backgroundColor: "rgba(255, 255, 255, 0.85)",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 4,
    elevation: 2,
  },
  headerCenter: {
    flex: 1,
    alignItems: "center",
    gap: 4,
  },
  headerTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  headerTitle: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 22,
    color: COLORS.textPrimary,
  },
  headerSubtitle: {
    fontSize: 12,
    color: COLORS.textSecondary,
    textAlign: "center",
    lineHeight: 16,
    paddingHorizontal: 16,
  },
  headerSpacer: {
    width: 40,
  },

  progressBarContainer: {
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  progressBarTrack: {
    height: 5,
    backgroundColor: "rgba(0,0,0,0.06)",
    borderRadius: 3,
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    borderRadius: 3,
  },

  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },

  questionCard: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.card,
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 24,
    shadowColor: COLORS.primaryLight,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 4,
  },
  progressCounter: {
    fontFamily: "Fredoka_600SemiBold",
    fontSize: 14,
    color: COLORS.textSlateLight,
    textAlign: "center",
    marginBottom: 14,
    letterSpacing: 0.5,
  },
  questionText: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 21,
    color: COLORS.textPrimary,
    textAlign: "center",
    lineHeight: 28,
    marginBottom: 24,
    paddingHorizontal: 6,
  },

  optionsContainer: {
    gap: 12,
  },
  optionPill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.pillBg,
    borderRadius: RADIUS.buttonFooter,
    paddingVertical: 14,
    paddingHorizontal: 18,
    gap: 12,
    borderWidth: 1.5,
    borderColor: "transparent",
  },
  optionPillSelected: {
    borderColor: COLORS.primaryVibrant,
    backgroundColor: COLORS.pillSelectedBg,
  },
  optionIcon: {
    width: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  optionText: {
    flex: 1,
    fontFamily: "Fredoka_600SemiBold",
    fontSize: 14.5,
    color: COLORS.textPrimary,
    lineHeight: 20,
  },
  optionTextSelected: {
    color: COLORS.primaryVibrant,
  },

  footer: {
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 20,
    paddingBottom: 24,
    paddingTop: 8,
  },
  prevButton: {
    flex: 1,
    height: 52,
    borderRadius: RADIUS.buttonFooter,
    backgroundColor: COLORS.white,
    borderWidth: 1.5,
    borderColor: COLORS.borderLight,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    gap: 6,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  prevButtonDisabled: {
    opacity: 0.45,
    shadowOpacity: 0,
    elevation: 0,
  },
  prevButtonText: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 16,
    color: COLORS.textPrimary,
  },
  prevButtonTextDisabled: {
    color: COLORS.textMuted,
  },
  nextButton: {
    flex: 1,
    height: 52,
    borderRadius: RADIUS.buttonFooter,
    overflow: "hidden",
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.28,
    shadowRadius: 8,
    elevation: 4,
  },
  nextButtonDisabled: {
    shadowOpacity: 0.05,
    elevation: 0,
  },
  nextButtonGradient: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    gap: 6,
    borderRadius: RADIUS.buttonFooter,
  },
  nextButtonText: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 16,
    color: COLORS.white,
  },

  toastContainer: {
    position: "absolute",
    bottom: 110,
    left: 24,
    right: 24,
    backgroundColor: COLORS.textPrimary,
    borderRadius: RADIUS.cardSmall,
    paddingVertical: 16,
    paddingHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 10,
  },
  toastText: {
    fontFamily: "Fredoka_600SemiBold",
    fontSize: 15,
    color: COLORS.white,
    flex: 1,
  },
});
