import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFF5F7",
  },
  gradientBackground: {
    ...StyleSheet.absoluteFillObject,
  },
  safeArea: {
    flex: 1,
  },

  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 12,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.8)",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 4,
    elevation: 2,
  },
  headerCenter: {
    flex: 1,
    alignItems: "center",
    gap: 4,
  },
  headerTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  headerTitle: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 22,
    color: "#1E1B26",
  },
  headerSubtitle: {
    fontSize: 12,
    color: "#64748B",
    textAlign: "center",
    lineHeight: 16,
    paddingHorizontal: 16,
  },
  headerSpacer: {
    width: 40,
  },

  progressBarContainer: {
    paddingHorizontal: 20,
    marginBottom: 12,
  },
  progressBarTrack: {
    height: 5,
    backgroundColor: "rgba(0,0,0,0.06)",
    borderRadius: 3,
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    borderRadius: 3,
  },

  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },

  questionCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 28,
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 20,
    shadowColor: "#FF8FA3",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 4,
  },

  illustrationContainer: {
    width: "100%",
    marginBottom: 16,
    borderRadius: 20,
    overflow: "hidden",
  },

  progressCounter: {
    fontFamily: "Fredoka_600SemiBold",
    fontSize: 13,
    color: "#64748B",
    textAlign: "center",
    marginBottom: 8,
    letterSpacing: 0.5,
  },

  questionText: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 21,
    color: "#1E1B26",
    textAlign: "center",
    lineHeight: 28,
    marginBottom: 20,
    paddingHorizontal: 4,
  },

  optionsContainer: {
    gap: 12,
  },
  optionPill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FBF3F4",
    borderRadius: 26,
    paddingVertical: 14,
    paddingHorizontal: 18,
    gap: 12,
    borderWidth: 1.5,
    borderColor: "transparent",
  },
  optionPillSelected: {
    borderColor: "#FF2D6C",
    backgroundColor: "#FFE9EF",
  },
  optionEmojiWrap: {
    width: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  optionEmoji: {
    fontSize: 20,
  },
  optionText: {
    flex: 1,
    fontFamily: "Fredoka_600SemiBold",
    fontSize: 15,
    color: "#1E1B26",
    lineHeight: 20,
  },
  optionTextSelected: {
    color: "#FF2D6C",
  },

  footer: {
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 20,
    paddingBottom: 24,
    paddingTop: 8,
  },
  prevButton: {
    flex: 1,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#FFFFFF",
    borderWidth: 1.5,
    borderColor: "#F1F5F9",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    gap: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  prevButtonDisabled: {
    opacity: 0.45,
    shadowOpacity: 0,
    elevation: 0,
  },
  prevButtonText: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 16,
    color: "#1E1B26",
  },
  prevButtonTextDisabled: {
    color: "#94A3B8",
  },
  nextButton: {
    flex: 1,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#FF2D6C",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    gap: 6,
    shadowColor: "#FF2D6C",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.28,
    shadowRadius: 8,
    elevation: 4,
  },
  nextButtonDisabled: {
    backgroundColor: "#CBD5E1",
    shadowOpacity: 0.05,
    elevation: 0,
  },
  nextButtonText: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 16,
    color: "#FFFFFF",
  },

  submittedOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(30, 27, 38, 0.6)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
    zIndex: 99,
  },
  submittedCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 28,
    padding: 26,
    alignItems: "center",
    width: "100%",
    maxWidth: 340,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 8,
  },
  submittedIconWrap: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: "#FFE9EF",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
  },
  submittedTitle: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 22,
    color: "#1E1B26",
    textAlign: "center",
    marginBottom: 8,
  },
  submittedSubtitle: {
    fontFamily: "Fredoka_400Regular",
    fontSize: 14,
    color: "#64748B",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 22,
  },
  submittedButton: {
    width: "100%",
    height: 50,
    borderRadius: 25,
    backgroundColor: "#FF2D6C",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#FF2D6C",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  submittedButtonText: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 16,
    color: "#FFFFFF",
  },
});
