import { StyleSheet } from "react-native";
import { COLORS } from "@/constants/colors";

export const invitePartnerStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  gradientBackground: {
    ...StyleSheet.absoluteFillObject,
  },
  safeArea: {
    flex: 1,
    paddingHorizontal: 24,
    justifyContent: "space-between",
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingTop: 12,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    justifyContent: "center",
    alignItems: "center",
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    paddingVertical: 16,
  },
  titleContainer: {
    alignItems: "center",
    marginBottom: 28,
  },
  title: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 30,
    lineHeight: 38,
    color: "#FFFFFF",
    textAlign: "center",
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 15,
    lineHeight: 22,
    color: COLORS.textDim,
    textAlign: "center",
    paddingHorizontal: 12,
  },
  codeCard: {
    backgroundColor: "rgba(255, 255, 255, 0.06)",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
    paddingVertical: 26,
    paddingHorizontal: 20,
    alignItems: "center",
    marginBottom: 18,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 4,
  },
  codeText: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 42,
    letterSpacing: 6,
    color: "#FFFFFF",
  },
  expiryText: {
    fontFamily: "Fredoka_400Regular",
    fontSize: 13,
    color: "#A78BFA",
    marginTop: 8,
  },
  inviteButton: {
    height: 58,
    borderRadius: 29,
    overflow: "hidden",
    shadowColor: "#FF4D6D",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 6,
    marginBottom: 22,
  },
  inviteButtonGradient: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 29,
  },
  inviteButtonIcon: {
    marginRight: 10,
  },
  inviteButtonText: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 17,
    color: "#FFFFFF",
    letterSpacing: 0.3,
  },
  dividerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 22,
    paddingHorizontal: 8,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: "rgba(255, 255, 255, 0.12)",
  },
  dividerText: {
    marginHorizontal: 14,
    fontSize: 13,
    color: "#8E7B8C",
  },
  partnerInputSection: {
    marginBottom: 20,
  },
  partnerInputHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  inputLabel: {
    fontFamily: "Fredoka_600SemiBold",
    fontSize: 14,
    color: "#FFFFFF",
  },
  pasteButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
  },
  pasteButtonText: {
    fontFamily: "Fredoka_600SemiBold",
    fontSize: 12,
    color: "#FFFFFF",
    marginLeft: 6,
  },
  inputCard: {
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
    height: 64,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 16,
  },
  textInput: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 26,
    letterSpacing: 5,
    color: "#FFFFFF",
    textAlign: "center",
    width: "100%",
  },
  connectButton: {
    height: 52,
    borderRadius: 26,
    overflow: "hidden",
    marginTop: 14,
  },
  connectButtonGradient: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  connectButtonText: {
    fontFamily: "Fredoka_700Bold",
    fontSize: 16,
    color: "#FFFFFF",
  },
  footer: {
    paddingBottom: 24,
    alignItems: "center",
  },
  laterButton: {
    paddingVertical: 10,
    paddingHorizontal: 20,
  },
  laterButtonText: {
    fontFamily: "Fredoka_600SemiBold",
    fontSize: 15,
    color: "#BFA8BC",
    textDecorationLine: "underline",
    letterSpacing: 0.2,
  },
});
